### ISSUE TITLE
Keyword for forcing file content search

### ISSUE THREAD

**Issue by agrecaBAS** [chunqiuyiyu/bing-chat-prompt-keywords#1]
Are you aware of a keyword that forces Copilot (formerly Bing Chat) to search PDFs?

**Comment by chunqiuyiyu** [comment]
Sorry I don't know the specific keyword to search pdf, maybe you can convert the pdf to txt and let bing recognize it

**Comment by agrecaBAS** [comment]
The recognizing isn't actually the problem but forcing it to search the document instead of trying to search the web would be nice. I pretty much just use "According to this document" as the keyword each time but I wasn't sure if there was a shorter way.

Thanks anyway!
